(module (import "spectest" "print_i32" (func $printi (param $i i32)))
 (memory $rael.memory (export "memory") 1)
 (table $rael.global funcref (elem))
 (func $fib.fn/1 (export "fib") (param $n/1 i32) (result i32)
  (local.get $n/1) (i32.const 0) (i32.eq)
  (if (result i32) (then (i32.const 1))
   (else (local.get $n/1) (i32.const 1) (i32.eq)
    (if (result i32) (then (i32.const 1))
     (else (local.get $n/1) (i32.const 1) (i32.sub) (call $fib.fn/1)
      (local.get $n/1) (i32.const 2) (i32.sub) (call $fib.fn/1) (i32.add))))))
 (func $*init*/2 (local $a/2 i32) (i32.const 33) (local.tee $a/2)
  (call $fib.fn/1) (call $printi))
 (export "_start" (func $*init*/2)))